spring:
    application:
        name: merch-service
    jackson:
        serialization:
            fail-on-empty-beans: false
    mvc:
        throw-exception-if-no-handler-found: true
    web:
        resources:
            add-mappings: false

management:
    endpoint:
        health:
            enabled: true